@AC_API_HostAddress = http://localhost:5295

POST {{AC_API_HostAddress}}/auth/register
Content-Type: application/json
{
    "Name": "Василий Иванов",
    "Surname": "Иванов",
    "Password": "StrongPassw0rd!"
}

###

POST {{AC_API_HostAddress}}/auth/login
Content-Type: application/json

{
    "Name": "Василий Иванов",
    "Password": "StrongPassw0rd!"
}